version: '3.9'

services:
  # Vue.js application service
  vuejs-app:
    build: .
    ports:
      - "8081:80"
    restart: unless-stopped

  # Nginx service
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - vuejs-app
